name: golang-gin ci-cd

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write   # Ensure write access to the repository
  pages: write      # Ensure write access to GitHub Pages

jobs:
  build:
    name: Build gin exec
    runs-on: ubuntu-latest

    steps:
    # checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # setup golang environment
    - name: Setup Golang Env
      uses: actions/setup-go@v4
      with:
        go-version: 1.21 # replace with any version

    # Caching go modules
    - name: Caching Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Build Application
    - name: Build application
      run: go build -o build/myapp main.go

    # upload build-artifacts
    - name: Upload Build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: myapp
        path: build/myapp

  deploy:
    name: Deploy golang-gin application
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Git for deployment (use GitHub token for push access)
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://github.com/${{ github.repository }}.git

    # Deploy to GitHub Pages using the GITHUB_TOKEN for authentication
    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the secret GitHub token
      run: |
        git add .
        git diff --cached --quiet || git commit -m "Deploy to gh-pages"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
